//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaytNTayt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public System.Guid ID { get; set; }
        public System.Guid CustomerİD { get; set; }
        public System.Guid ProductID { get; set; }
        public Nullable<System.Guid> ShippingID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Shipping Shipping { get; set; }
    }
}
